# Generated by Django 3.0.2 on 2020-01-31 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='my_rides',
        ),
    ]
