# Generated by Django 3.0.2 on 2020-02-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200201_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='plate_id',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
